global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "train-ticketing-prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:9090"]
    metrics_path: "/metrics"

  - job_name: "train-ticketing-springboot"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:1000" ]
    metrics_path: "/actuator/prometheus"

  - job_name: "train-ticketing-node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:9100" ]

  - job_name: "train-ticketing-mysql-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:9104" ]
    metrics_path: "/metrics"

  - job_name: "train-ticketing-redis-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:9121" ]
    metrics_path: "/metrics"

#  - job_name: "train-ticketing-logstash-exporter"
#    scrape_interval: 5s
#    static_configs:
#      - targets: [ "host.docker.internal:9304" ]
#    metrics_path: "/metrics"