version: "3.9"
services:
  # Kafka visualization tool
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"  # Map Kafka UI to port 8080 on the host
    depends_on:
      kafka1:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: env-ddd      # Cluster name
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092  # Cluster bootstrap servers
      DYNAMIC_CONFIG_ENABLED: 'true'
  #    networks:
  #      - local-network-2025

  # Kafka cluster
  kafka1:
    image: 'bitnami/kafka:3.5'
    container_name: kafka1
    ports:
      - 9192:9092  # Broker port
      - 9193:9094    # Controller port
    environment:
      ### General configurations
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # Define Kafka server-side socket listening ports
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      # Define security protocols
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      # Set advertised listener
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://192.168.1.115:9193,PLAINTEXT://kafka1:9092
      # Interbroker listener name
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Cluster ID for Kafka, must be the same across the cluster. Use a generated UUID
      - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
      # Cluster address
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093
      # Allow PLAINTEXT listener (default is false; not recommended for production)
      - ALLOW_PLAINTEXT_LISTENER=yes
      # Set maximum and initial memory for the broker
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M
      # Enable auto-creation of topics
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      # Message retention period (in milliseconds), set to 7 days
      - KAFKA_LOG_RETENTION_MS=604800000
      ### Broker configurations
      # Define external access address (host IP and port) -> get Ip: run docker inspect kafka1
      # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA1_IP}:9092
      # Broker ID, must be unique
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
    volumes:
      - ./data/bitnami/kafka1:/bitnami/kafka
    #    networks:
    #      - local-network-2025
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092" ]
      interval: 5s
      timeout: 10s
      retries: 10
#networks:
#  local-network-2025:
#    driver: bridge